---
title: "Data Visualizations"
output:
  html_document:
    css: custom.css
toc: false
# toc_float: true
---
## Weekend Box Office (1977-2023)

<iframe src="https://anthonymoubarak.georgetown.domains/BoxOfficeTime/index.html" frameborder="0" width="100%" height="450"></iframe>

A notable and broad observation is the evolution of weekend box office results from 1977 to 2023. The initial and unmistakable trend is the nearly exponential growth in weekly box office earnings over time. In the past, weekend box office earnings were typically in the range of a couple of million dollars, whereas nowadays, they often reach into the tens or even hundreds of millions.

These results are in line with the significant expansion of the movie industry over the last few decades. Ticket prices have risen in response to inflation, and movies have become a much more substantial and influential part of popular culture as time has progressed.

Regarding seasonality and cyclic patterns, it appears that there are consistent recurring cycles throughout this time period, although a more detailed analysis of these patterns will be conducted in the EDA (Exploratory Data Analysis) section. Additionally, there seems to be a continuous increase in the difference between the lowest and highest points, and this gap appears to be widening as time goes on.

## Weekend Box Office Winners per Genre

<iframe src="https://anthonymoubarak.georgetown.domains/BoxOfficeGenres/index.html" frameborder="0" width="100%" height="600"></iframe>

One of the most obvious facts is that certain types of movies consistently outperform others at the box office. For instance, franchise movies, such as superhero films, have consistently demonstrated stronger performance compared to other genres. Remarkably, when we examine the top 10 highest-grossing movies of all time, only one, "Titanic," does not belong to a major intellectual property or franchise. Therefore, it is sensible to analyze the top box office performers within different genres over time.

The animated plot presented above illustrates the genres that have dominated the box office each year. Surprisingly, the number of films winning the weekend box office in various genres varies widely from year to year. Genres like Action and Drama often cover the majority of box office winners. However, this pattern can be explained by the infrequent release of big franchise movies. Producing such films entails significant costs and time, resulting in less frequent releases. Conversely, there is a consistent influx of drama and low-budget movies being released every week, contributing to a more diverse distribution of box office results across genres.

## Movie Reviews of Top Box Office Earners

<iframe src="https://anthonymoubarak.georgetown.domains/BoxOfficeRT/index.html" frameborder="0" width="100%" height="420"></iframe>

Another layer of analysis worth exploring is whether critically acclaimed movies tend to top the box office or not. To investigate this, the plot above utilizes data from Rotten Tomatoes, the most widely recognized platform for aggregating critic movie reviews. On Rotten Tomatoes, movies are categorized as either "Fresh" or "Rotten." "Fresh" signifies movies with ratings above 60%, indicating that 60% or more of critics gave the film a positive review, while the rest are considered "Rotten."

Examining the distribution of movies in these two categories is quite intriguing. It reveals an almost even split, with roughly half of the movies classified as "Fresh" and the other half as "Rotten." This suggests that there isn't an overwhelming reliance on a movie's critical reception for its opening weekend success. However, the story may differ when considering a movie's long-term box office performance, as a film is less likely to have staying power if it doesn't receive positive reviews from critics.

This observation could be a subtle indication that factors like hype and marketing might exert a more significant influence on a movie's opening weekend performance compared to critic ratings. For instance, franchises like "Fast & Furious" consistently perform well in their opening weekends despite not always receiving favorable critical acclaim.

## Studio Financial Analysis
<iframe src="https://anthonymoubarak.georgetown.domains/stocks.html" width="100%" height="600" frameborder="0"></iframe>


<iframe src="https://anthonymoubarak.georgetown.domains/stocks_norm.html" width="100%" height="600" frameborder="0"></iframe>


<iframe src="https://anthonymoubarak.georgetown.domains/box_office.html" width="100%" height="600" frameborder="0"></iframe>

This analysis delves into the financial sector of the movie industry, specifically highlighting stock performances of major Hollywood studios. Our focus is on Disney, Paramount, Lionsgate, Warner Bros, and Netflix. While there are numerous studios in the industry, these selected entities provide a comprehensive insight into the sector's financial landscape. Notably, we've included Netflix to represent the growing impact of streaming services in this traditionally cinema-focused industry.

A standout observation is Netflix's meteoric rise in stock prices. The growth trajectory of Netflix's stock, in many instances, has eclipsed the combined growth of some of the other studios. This surge underscores investors' confidence in Netflix's future potential. It suggests a broader industry trend where streaming platforms could challenge, if not dethrone, traditional movie theaters as the primary venues for film viewing. The rise of Netflix is not just a testament to its success as a streaming service but positions it as a formidable player in the entertainment sector, transcending its initial label as merely a tech company.

However, a nuanced view, especially when analyzing normalized stock prices, reveals a consistent growth story for Disney. Unlike the erratic stock performances of other studios, Disney's stock has shown steady growth. Curiously, despite Netflix's overwhelming growth in absolute terms, when assessed against normalized metrics, its behavior mirrors that of other major studios. A potential explanation could be the cyclical nature of the industry, marked by periods of hit releases and lulls, impacting all players uniformly over time.

On the cinematic front, Paramount historically dominated the charts, boasting the highest number of weekly box office toppers for an extended period. However, the tide seemed to turn in favor of Disney. This shift is unsurprising, given Disney's strategic acquisitions over the years. Their portfolio now includes powerhouses like Marvel, Lucasfilm, and Pixar. The consistent release of blockbuster titles from these franchises has cemented Disney's position at the pinnacle of box office charts.

In summary, while streaming giants like Netflix are making waves in the stock market, traditional studios, especially Disney, with its strategic acquisitions and diverse portfolio, continue to hold their ground, both in stock performance and cinematic dominance.