project:
  type: website

website:
  title: "Mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: data_sources.qmd
        text: Data Sources
      - href: eda.qmd
        text: EDA
      - href: data_viz.qmd
        text: Data Vizes in TS
      - href: arimas.qmd
        text: ARIMAS
      - href: arimax.qmd
        text: AIRMAX
      - href: dl.qmd
        text: Deep Learning
      - href: financial.qmd
        text: Financial


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



