---
project:
  type: website

website:
  title: "Time Series"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
---

# About Me 

My name is Anthony and I am from Lebanon. I did my undergraduate studies at the Lebanese American University and majored in Industrial Engineering. Halfway through my undergrad, I developed an interest in Data Science and decided to study it on my own via online courses and personal projects to make sure it is the field I wanted to work in, which turned out to be the case as I was instantly captivated by the field’s interdisciplinary nature that could be applicable in a variety of industries. 

I am a very multi-dimensional person and have several hobbies including CrossFit (and many other forms of fitness), playing the electric guitar, watching podcasts on various topics (a very underrated form of intellect in my opinion), and many more. As for my passions, I am a film enthusiast and could spend hours talking about movies and how they mirror humans and society in general, a Metalhead (from indie Red Hot Chili Peppers type of rock all the way to SlipKnot metal style), and I am also very interested in psychology and philosophy. 

I firmly believe that I should eventually work at a company that I actually believe in and in their products, as I aim to look at my job as my purpose, in the sense of contributing to an environment that serves the world products that are impactful and that matter. That being said, upon graduation I see myself working as a Data Scientist in an industry that revolves around a passion of mine. Netflix, Spotify, WHOOP, are examples of companies that I would love to work in as I would be directly contributing to the world of film,music, fitness.
